#!/bin/bash

printf "\n* Container prerm...\n"
printf "\n* Cleanup...\n"
if podman ps | awk '{print $2}' | grep -q ^localhost/dns$; then
    podman stop dns
fi

if podman images | awk '{print $1}' | grep -q ^localhost/dns$; then
    podman rmi -f dns
fi

exit 0
